# sets up common build tools for the windows build machines before build

parameters:
- name: arch
  type: string

- name: DoEsrp
  displayName: Run code sign tasks? Must be true if you are doing an Onnx Runtime release.
  type: boolean
  default: true
  
- name: artifactName
  displayName: artifactName，like 'onnxruntime_nodejs-win-x64-1.6.0'
  type: string
  default: ''
  
- name: artifactNameNoVersionString
  type: string
  default: 'onnxruntime_nodejs-win-x64'

steps:
    - template: win-esrp-dll.yml
      parameters:
        FolderPath: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\${{ parameters.arch }}'
        DisplayName: 'ESRP - Sign Node.js binding binaries'
        DoEsrp: ${{parameters.DoEsrp}}
        Pattern: '*.node'

    - task: CmdLine@2
      displayName: 'Copy build artifacts for zipping'
      inputs:
        script: |
          mkdir $(Build.BinariesDirectory)\${{parameters.artifactName}}
          copy $(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\${{ parameters.arch }}\onnxruntime_binding.node $(Build.BinariesDirectory)\${{parameters.artifactName}}

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)\${{parameters.artifactName}}'
        includeRootFolder: true
        archiveType: 'zip' # Options: zip, 7z, tar, wim
        archiveFile: '$(Build.ArtifactStagingDirectory)\${{parameters.artifactName}}.zip' 
        replaceExistingArchive: true 

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)\${{parameters.artifactName}}.zip' 
        artifactName: '${{parameters.artifactNameNoVersionString}}'
