parameters:
- name: NpmTag
  type: string
  default: 'dev'

jobs:
- job: publish_onnxruntime_web
  pool: 'Win-CPU-2019'

  timeoutInMinutes: 30
  workspace:
    clean: all
  steps:
  - checkout: none
    submodules: false
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'NPM_packages'
      path: $(Pipeline.Workspace)\NPM_packages
    displayName: 'Get packed artifacts'
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
  - script: |
     npm publish ... TBD
    workingDirectory: '$(Pipeline.Workspace)\NPM_packages'
    displayName: 'npm publish ... TBD'
  - template: component-governance-component-detection-steps.yml
    parameters :
      condition : 'succeeded'
  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
