jobs:
- job: Linux_Test
  timeoutInMinutes: 60
  workspace:
    clean: all
  pool: centos7gpu
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact'
    inputs:
      buildType: specific
      project: '2a773b67-e88b-4c7f-9fc0-87d31fea8ef2'
      definition: 12
      buildVersionToDownload: specific
      pipelineId: 516871      
      artifactName: 'drop-linux'
      targetPath: '$(Build.BinariesDirectory)/Release'

  - task: CmdLine@2
    inputs:
      script: |
         set -e -x
         # We assume the machine doesn't have gcc and python development header files
         sudo rm -f /build /onnxruntime_src
         sudo ln -s $(Build.SourcesDirectory) /onnxruntime_src
         python3 -m pip uninstall -y ort-nightly-gpu ort-nightly onnxruntime onnxruntime-gpu -qq
         cp $(Build.SourcesDirectory)/tools/ci_build/github/linux/docker/scripts/manylinux/requirements.txt $(Build.BinariesDirectory)/requirements.txt
         # Test ORT with the latest ONNX release.
         sed -i 's/git+http:\/\/github\.com\/onnx\/onnx.*/onnx==1.9.0/' $(Build.BinariesDirectory)/requirements.txt
         python3 -m pip install -r $(Build.BinariesDirectory)/requirements.txt
         python3 -m pip install $(Build.BinariesDirectory)/Release/dist/*.whl
         ln -s /data/models $(Build.BinariesDirectory)
         cd $(Build.BinariesDirectory)/Release
         # Restore file permissions
         xargs -a $(Build.BinariesDirectory)/Release/perms.txt chmod a+x
         cd $(Build.SourcesDirectory)/java
         /usr/local/gradle/bin/gradle "cmakeCheck" "-DcmakeBuildDir=$(Build.BinariesDirectory)/Release" "-DUSE_CUDA=1"
         cd /tmp
         python3 $(Build.SourcesDirectory)/tools/ci_build/build.py \
              --build_dir $(Build.BinariesDirectory) --cmake_generator Ninja \
              --config Release --test \
              --skip_submodule_sync \
              --build_shared_lib \
              --parallel \
              --build_wheel \
              --enable_onnx_tests --use_cuda --cuda_version=11.4 --cuda_home=/usr/local/cuda-11.4 --cudnn_home=/usr/local/cuda-11.4 \
              --enable_pybind --build_java --ctest_path ''

  - template: templates/component-governance-component-detection-steps.yml
    parameters:
      condition: 'succeeded'
