parameters:
- name: NpmPublish
  displayName: 'NPM packages publish configuration'
  type: string
  values:
  - 'no'
  - 'nightly (@dev)'
  - 'release candidate (@rc)'
  - 'production (@latest)'
  - 'custom'
  default: no

variables:
- name: CmdParams
  value: '$[variables.CmdParams]'
- name: VersionSuffix
  value: '$[variables.VersionSuffix]'
- name: NpmTag
  value: '$[variables.NpmTag]'

stages:
- stage: Extract_commit
  jobs:
  - job: Extract_commit
    pool: 'Win-CPU-2019'
    timeoutInMinutes: 30
    workspace:
      clean: all
    steps:
    - checkout: none
      fetchDepth: 1
      submodules: false
    - script: |
        echo.$(Build.SourceVersion)
        echo.$(Build.SourceVersion)>$(Build.ArtifactStagingDirectory)\__commit.txt
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: '__commit'
        targetPath: '$(Build.ArtifactStagingDirectory)'

- stage: Build_wasm_Debug
  dependsOn: Extract_commit
  jobs:
  - template: templates/win-wasm-ci.yml
    parameters:
      CommitOverride: true
      BuildConfig: 'Debug'
      CmdParams: '$(CmdParams)'

- stage: Build_web_Debug
  dependsOn: Build_wasm_Debug
  jobs:
  - template: templates/win-web-ci.yml
    parameters:
      CommitOverride: true
      BuildConfig: 'Debug'

- stage: Build_wasm_Release
  dependsOn: Extract_commit
  jobs:
  - template: templates/win-wasm-ci.yml
    parameters:
      CommitOverride: true
      BuildConfig: 'Release'
      CmdParams: '--skip_tests --disable_wasm_exception_catching --disable_rtti $(CmdParams)'

- stage: Build_web_Release
  dependsOn: Build_wasm_Release
  jobs:
  - template: templates/win-web-ci.yml
    parameters:
      NpmVersionSuffix: '$(VersionSuffix)'
      CommitOverride: true
      BuildConfig: 'Release'

- stage: Test_web_BrowserStack
  dependsOn: Build_wasm_Release
  jobs:
  - template: templates/web-browserstack-ci.yml
    parameters:
      CommitOverride: true

- stage: Test_web_MultiBrowsers
  dependsOn: Build_wasm_Release
  jobs:
  - template: templates/win-web-multi-browsers.yml
    parameters:
      CommitOverride: true

- stage: Publish_package
  dependsOn:
  - Build_web_Release
  - Test_web_BrowserStack
  - Test_web_MultiBrowsers
  condition:
    and(succeeded(), or(and(eq(variables['Build.Reason'], 'Scheduled'),
                            eq(variables['Build.SourceBranch'], 'refs/heads/master')
                           ),
                        and(eq(variables['Build.Reason'], 'Manual'),
                            eq('${{ parameters.DoPublish }}', true)
                           )
                       )
       )
  jobs:
  - template: templates/win-web-publish.yml
    parameters:
      NpmTag: '$(NpmTag)'
