stages:
- stage: Extract_commit
  jobs:
  - job: Extract_commit
    pool: 'Win-CPU-2019'
    timeoutInMinutes: 30
    workspace:
      clean: all
    steps:
    - checkout: none
      fetchDepth: 1
      submodules: false
    - script: |
        echo.$(Build.SourceVersion)
        echo.$(Build.SourceVersion)>$(Build.ArtifactStagingDirectory)\__commit.txt
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: '__commit'
        targetPath: '$(Build.ArtifactStagingDirectory)'

- stage: Build_wasm_Debug
  dependsOn: Extract_commit
  jobs:
  - template: templates/win-wasm-ci.yml
    parameters:
      CommitOverride: true
      BuildConfig: 'Debug'
      CmdParams: ''

- stage: Build_web_Debug
  dependsOn: Build_wasm_Debug
  jobs:
  - template: templates/win-web-ci.yml
    parameters:
      NpmVersionSuffix: "-dev.${YYYYMMDD}.${I}"
      CommitOverride: true
      BuildConfig: 'Debug'

- stage: Build_wasm_Release
  dependsOn: Extract_commit
  jobs:
  - template: templates/win-wasm-ci.yml
    parameters:
      CommitOverride: true
      BuildConfig: 'Release'
      CmdParams: '--skip_tests --disable_wasm_exception_catching --disable_rtti'

- stage: Build_web_Release
  dependsOn: Build_wasm_Release
  jobs:
  - template: templates/win-web-ci.yml
    parameters:
      NpmVersionSuffix: "-dev.${YYYYMMDD}.${I}"
      CommitOverride: true
      BuildConfig: 'Release'

- stage: Publish_package
  dependsOn: Build_web_Release
  jobs:
  - template: templates/win-web-publish.yml
    parameters:
      NpmTag: "dev"
