[tool.black]
line-length = 120
# extend-exclude needs to be a regular expression
extend-exclude = "cmake|onnxruntime/core/flatbuffers/"
target-version = ["py37", "py38", "py39", "py310"]

[tool.isort]
profile = "black"
line_length = 120
extend_skip_glob = [
    "cmake/*",
    "orttraining/*",
    "onnxruntime/core/flatbuffers/*",
]

[tool.pydocstyle]
convention = "google"

[tool.pylint.'MESSAGES CONTROL']
disable = ["format", "line-too-long", "import-error", "no-name-in-module"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
warn_redundant_casts = true
warn_return_any = true
show_error_codes = true
show_column_numbers = true
check_untyped_defs = true
warn_unused_ignores = false

exclude = [
    "^onnxruntime/core/flatbuffers/\\.py$",
]
