name: Linux_CI
on:
  push:
    branches:
      - master
      - main
      - snnn/linuxci
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Onnxruntime-TVM:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
       - uses: actions/setup-python@v3
         with:
           python-version: '3.8.x'
           architecture: 'x64'
       - name: 'Setup TVM EP requirements'
         run: |
           set -e -x 
           sudo apt-get update
           sudo apt-get install -y libtinfo-dev zlib1g-dev build-essential libedit-dev libxml2-dev
           python3 -m pip install -r ${{ github.workspace }}/tools/ci_build/github/linux/tvm/requirements.txt
       - name: 'Build and Test'
         run: |
           python3 ${{ github.workspace }}/tools/ci_build/build.py --build_dir build --config Release --skip_submodule_sync --parallel --enable_pybind --disable_contrib_ops --disable_ml_ops --skip_onnx_tests --use_tvm --ctest_path ""
  Onnxruntime-CPU:
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-github-ubuntu-20-04-cpu"]
    steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
       - uses: actions/setup-python@v3
         with:
           python-version: '3.8.x'
           architecture: 'x64'
       - name: Azure CLI script
         uses: azure/CLI@v1
         with:
              inlineScript: |
                az login --identity
                az acr login -n onnxruntimebuildcache